### ISSUE TITLE
TWW Patch: Range check errors

### ISSUE THREAD

**Issue by Loreinator** [WeakAuras/LibRangeCheck-3.0#27] opened 2024-07-24 12:05 UTC
Error output whenever I target an enemy: 

Message: bad argument #1 to '?' (not a numerical value - Usage: local inRange = C_SpellBook.IsSpellBookItemInRange(spellBookItem [, targetUnit]))
Time: Wed Jul 24 07:52:37 2024
Count: 897
Stack: bad argument #1 to '?' (not a numerical value - Usage: local inRange = C_SpellBook.IsSpellBookItemInRange(spellBookItem [, targetUnit]))
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:89: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:88>
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:573: in function `checker'
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:786: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:781>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:861: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:842>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI_Enhanced/modules/datatexts/range.lua"]:27: in function <...ce/AddOns/ElvUI_Enhanced/modules/datatexts/range.lua:20>

Locals: index = 73
spellBank = "spell"
unit = "target"

**Comment by Stanzilla** [comment] 2024-07-24 12:06
Duplicate of https://github.com/WeakAuras/LibRangeCheck-3.0/issues/26

**Closed by Stanzilla** 2024-07-24 12:06 UTC
